#%RAML 1.0
title: Sandbox Ideas for RAML
version: v1
baseUri: http://api.samplehost.com/api4kb-proto
types:
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number
/helloWorld:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message" : "Hello World"
              }
